### ISSUE TITLE
Can't get anything to work on android 11 at least

### ISSUE THREAD

**Issue by nonetrix** [stephane-r/Youtube-Audio-Player#133]
nothing seems to work most of the time it doesn't show anything the most I got was thumbnails and etc couldn't play anything I know Google likes to break things so just so you know I'm on android 11

I've also tried different servers all are the same mostly if I go in my browser it's fine also a API token doesn't help just soft locks the app also has a random dialog box that just says close at the bottom

**Comment by stephane-r** [comment]
Hey @nonetrix 

I haven't tried the app on Android 11 (real device or emulator) yet. I would do a test on the preview version of Android Studio in order to have the Android 11 SDK and I will give you a feedback :)

Thank you :muscle:

**Comment by stephane-r** [comment]
Hi @nonetrix 

I've try HoloPlay on Android 11 emulator, and API with invidious.site instance work nice for me. I know several APIs have been having issues lately.

Do you still have the problem ?
