### ISSUE TITLE
Cannot login to instance. DialogEditToken throws unexpected token 

### ISSUE THREAD

**Issue by WNemencha** [stephane-r/Youtube-Audio-Player#134]
Hey,

Thanks for the cool app but I can't login, tried with multiple instances and different tokens but still JSON parse error. Something may have changed in API ?

See attached screenshots. I also share metrics & errors to the self hosted Sentry instance so you might find the error here ;)

Kind regards

![IMG_20201002_201407](https://user-images.githubusercontent.com/40295432/94956070-d6a69880-04eb-11eb-962d-228c8ac0d27d.jpg)

**Comment by WNemencha** [comment]
Seems to be related to anti-ddos page returning HTML instead of JSON 👎

**Comment by WNemencha** [comment]
Seems to be related to anti-ddos page returning HTML instead of JSON :/

![Screenshot_2020-10-02-20-43-30-778_br tiagohm restler](https://user-images.githubusercontent.com/40295432/94958514-f3dd6600-04ef-11eb-9f4d-7d2e9e61dcee.jpg)

**Comment by WNemencha** [comment]
Or it's the API itself that's broken 😕 
![Screenshot_2020-10-02-21-49-55-620_br tiagohm restler](https://user-images.githubusercontent.com/40295432/94964020-48d1aa00-04f9-11eb-9fc3-46b03af36d8b.jpg)

**Comment by stephane-r** [comment]
Hey @WNemencha 

It seems that a number of instances are having issues with their API over the past few days :/ 
I will work on a module to visually display the functional APIs :) 

For anti-ddos page, I don't think their API can be used with this check ?

**Comment by stephane-r** [comment]
I've try with invidious.site (but without token), this API work at this time.

**Comment by stephane-r** [comment]
Hey @WNemencha 

I'm working on new screen with all Invidious API listed. From this listing you'll be able to use API (more easier than now), and test the API by adding your token or test if the API is down.

This is in WIP for now.

Also, a bug with API URLs was found: some API URLs end with slash and others do not, which creates an error because the URL is not valid (e.g. https: // invidious.xyz//api/v1/top)

![image](https://user-images.githubusercontent.com/4712791/95023279-798e1c80-067c-11eb-878e-c6fdfdf789f8.png)

**Comment by WNemencha** [comment]
@stephane-r Thanks for the fix / new screen ! This IS definitly a great thing :D

**Comment by WNemencha** [comment]
Also I've updated to the new version and now I get this error when trying to authenticate with token (snopyta instance).
![Screenshot_2020-10-17-02-13-52-460_com holoplay](https://user-images.githubusercontent.com/40295432/96323695-96ccce80-101e-11eb-8d1d-4a47c95488a1.jpg)

**Comment by stephane-r** [comment]
Yop @WNemencha 

I've run some test on same instance, it's okay for me. Can you try with new token generate with [this URL](https://invidious.snopyta.org/authorize_token?scopes=:*) ? 

The error message is not very informative. I'll publish new patch for show API error message :)
