### ISSUE TITLE
Token error "Unexpected char"

### ISSUE THREAD

**Issue by Elbullazul** [stephane-r/Youtube-Audio-Player#139]
I'm having problems adding in my [skyn3t](https://inv.skyn3t.in) token, as this screenshot shows:

![Screenshot_20210503-143419_HoloPlay](https://user-images.githubusercontent.com/15310985/116918555-0c486700-ac1e-11eb-8895-eff722d1f147.jpg)

I also want to ask if there is a way to disable autoplay when selecting a single video

**Comment by stephane-r** [comment]
Hey @Elbullazul 

Have you same issue if you trying with other instance ?

I'll try with skynet tomorrow :)

**Comment by Elbullazul** [comment]
I had previously tried with [Puffyan](https://vid.puffyan.us) and got the same message but with 'line 1, column 1'

**Comment by stephane-r** [comment]
Hey @Elbullazul 

I've same result with App and Insomia. I've found this issue from Invidious repo : https://github.com/iv-org/invidious/issues/1637

I can't seem to know if the fix is ​​operational or if the instances are not up to date :/

**Comment by Elbullazul** [comment]
I tried with YTPrivate and it is still an issue. I'll see if I open an issue on the invidious repo.

Thanks for the help :D
