### ISSUE TITLE
F-Droid failed to build

### ISSUE THREAD

**Issue by linsui** [stephane-r/Youtube-Audio-Player#144]
https://gitlab.com/linsui/fdroiddata/-/jobs/1322208495

Could you please take a look? Thanks!

**Comment by stephane-r** [comment]
Hey @linsui 

Thank for issue. Mmm i don't know if the problem is with Hermes. 

For update fdroid config, i need only submit PR with new yaml ?

**Comment by linsui** [comment]
Yes, just update the yaml and oprn an MR. Thanks!

**Comment by stephane-r** [comment]
Hey @linsui 

MR created :) https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9195

I've added hermes-engine folder on scanignore. Hemes is enabled from latest version :)
