### ISSUE TITLE
Show all labels on the bottom bar

### ISSUE THREAD

**Issue by cloudrac3r** [stephane-r/Youtube-Audio-Player#145]
Currently on the application bottom navigation bar, only the currently selected item shows the label, which makes it more difficult than it needs to be to get to the desired section, especially when the icons are not indicative of the content (headphones and microphone for playlists).

I suggest making the labels on all items visible at all times, which would make the application easier to use and more accessible for everyone.

I looked at the documentation for the react native navigation bar and I think you need to set the option `shifting` to `false` as described here: https://reactnavigation.org/docs/material-bottom-tab-navigator/#shifting

I am a developer on other projects, but I do not know how to set up an environment for android app development, so even though I would love to make this change myself, I don't know how.

Thank you!

**Comment by stephane-r** [comment]
Hello 😄 

I'll add this on the next release (parameter available on settings screen i think)

**Comment by cloudrac3r** [comment]
awesome! I'm glad
