### ISSUE TITLE
Add some basic documentation

### ISSUE THREAD

**Issue by mariobrostech** [stephane-r/Youtube-Audio-Player#146]
Hello,

As someone who knows essentially nothing about Invidious besides some of the available frontends, I feel like it would be helpful to have a basic configuration tutorial listed in the repo's README or written in the GitHub Wiki and referenced in the README.

Would someone who knows a thing or two about Invidious from more of an API perspective be interested in doing this? It would be extremely helpful for newbies to Invidious and would probably give this app some more traction.

Thanks in advance for your consideration!

**Comment by DWW256** [comment]
This.  I can't figure out for the life of me whether I'm even supposed to locate the API token for my desired instance or generate my own, let alone where to find such a thing in the first place.

**Comment by stephane-r** [comment]
Hey 😃 

Thank you for your proposal ! I will make a PR with an update of the README after the holidays.

I'll ping you 👍

**Comment by mariobrostech** [comment]
Awesome, thank you!

**Comment by stephane-r** [comment]
Hey guys,

I've add some informations about Invidious on README. Could you give me your opinion, do you have any other information in mind ?

https://github.com/stephane-r/HoloPlay/pull/153/files

Thank you !

**Comment by DWW256** [comment]
👏👏 That's exactly what I was looking for!

**Comment by mariobrostech** [comment]
@stephane-r This is great, thank you!
