### ISSUE TITLE
Add ability to re-order tracks in playlists

### ISSUE THREAD

**Issue by DWW256** [stephane-r/Youtube-Audio-Player#151]
I mean, it would be nice.

**Comment by stephane-r** [comment]
Hey :)

Yes, this feature was in my TODO :smiley:  It will be added at the next release.

![holoplay-reorder-playlist](https://user-images.githubusercontent.com/4712791/130361871-b0b0b65f-365a-4256-94b6-1e59ba3b0b30.gif)
