### ISSUE TITLE
Customize the front page

### ISSUE THREAD

**Issue by DWW256** [stephane-r/Youtube-Audio-Player#155]
The biggest reason I switched to HoloPlay from NewPipe is that, being an audio-only player, HoloPlay presents itself much less as a potential source of distraction.  Being able to remove the "Most Popular" and "Trending" lists from the front page would be very helpful for making the app completely distraction-free.

Also—it would be nice to have the option to display a "my most played" list on the front page instead/as well.  🙂

**Comment by stephane-r** [comment]
Hello,

Mmmm yes, why not :) I'll look this soon.
