### ISSUE TITLE
Widget controls (suggestion)

### ISSUE THREAD

**Issue by luphoria** [stephane-r/Youtube-Audio-Player#157]
![Screenshot_20210926-231516.jpg](https://user-images.githubusercontent.com/60309933/134844677-ee158779-49fd-4e1c-b5ec-06444e3aa13f.jpg) 
These options take up almost all the space in the widget! I would recommend removing the skip buttons so that more text can fit.
Along with that, do you notice those buttons aren't consistent? The order should be `< % = % >` yet it is `< % = > %`

**Comment by stephane-r** [comment]
Hey @luphoria 

Mmmm yes, i think it's good update :) I'll check this soon, thank you !

**Comment by luphoria** [comment]
Oh to clarify by "skip" buttons i did mean the rewind/forward buttons (back 10/forward 30). Poor wording on my part!
![Screenshot_20210928-074322.jpg](https://user-images.githubusercontent.com/60309933/135089155-50341545-c504-4008-bf33-3c0aeb11efbc.jpg)
Example -- Spotify

**Comment by stephane-r** [comment]
Available on next release

Thank you :+1:
