### ISSUE TITLE
"Add playlist" button placing

### ISSUE THREAD

**Issue by ghost** [stephane-r/Youtube-Audio-Player#159]
Currently the "add playlist" button is in such place that it's very hard to tap on play/pause button from the song bar (see pic). Of course it's nothing major as you can simply switch card or use notification control but changing the button placing would still be nice.
![Screenshot_20211014-233003_HoloPlay](https://user-images.githubusercontent.com/91622727/137398995-cb29ed52-d14b-4341-ba16-8ff231c1bb6e.png)

**Comment by stephane-r** [comment]
This issue will update on 1.13.0 :) Thanks !
