### ISSUE TITLE
Swipe to open settings window conflicts with gestures control

### ISSUE THREAD

**Issue by user9931** [stephane-r/Youtube-Audio-Player#162]
I'm using gestures instead of buttons (as many users do) and spend some time to understand how to change settings until switched from "Navigation Gestures" to "Back, Home, Recent" buttons in Android settings.. Because swipe to left / swipe to right is working like "back" button

Please add a button to open the settings

**Comment by montvid** [comment]
It's good that there are no real settings to set at the moment so it is not that annoying.

**Comment by stephane-r** [comment]
Hey @thehotery 

I'm not sure understand, is the access to the settings in the left menu ?

**Comment by montvid** [comment]
Yes, one has to swipe left to access the menu. Sometimes it triggers the back button instead.

**Comment by stephane-r** [comment]
> Yes, one has to swipe left to access the menu. Sometimes it triggers the back button instead.

Okkk, Indeed 😄

**Comment by stephane-r** [comment]
Hey :) 

I've remove the Drawer menu and add 2 button actions (like Spotify) on the dashboard. I've update the Settings screen too.

## Dashboard

The first button navigate to the Invidious Instances screen. The second on the Settings screen.

<img src="https://user-images.githubusercontent.com/4712791/147831493-cadfdc44-8011-4e8a-b0e8-88e5bec1a389.png" data-canonical-src="https://user-images.githubusercontent.com/4712791/147831493-cadfdc44-8011-4e8a-b0e8-88e5bec1a389.png" width="350" />

## Settings

<img src="https://user-images.githubusercontent.com/4712791/147831496-25dc9d0a-4cb4-4242-933f-961310fd6b88.png" data-canonical-src="https://user-images.githubusercontent.com/4712791/147831496-25dc9d0a-4cb4-4242-933f-961310fd6b88.png" width="350" />

This update is available on the next release :smile: 

Thank you ! I hope that you will like it :+1:
